pipeline {
  agent any
  stages {
    stage('LINT HTML') {
      steps {
        sh 'tidy -q -e *.html'
      }
    }    
    
    stage('Upload to AWS') {
      steps {
        withAWS(region: 'us-east-1', credentials: 'aws-static') {
          sh 'echo "Uploading content with AWS creds"'
          s3Upload(pathStyleAccessEnabled: true, payloadSigningEnabled: true, file: 'index.html', bucket: 'my-s3-bucket-name')
        }

      }
    }



  }
}